In [140]:
!mamba install pandas

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 2.2556000000238416 seconds
All requested packages already installed.

In [141]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [142]:
df.head()

,Customer ID,Name,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,Diya Sharma,56,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,Isha Gupta,69,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,Kabir Singh,46,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,Diya Roy,32,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,Anaya Joshi,60,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [143]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.087436,59.764359,3.750065,25.351538
std,1125.977353,15.215450,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [144]:
df.isnull().sum()

Customer ID                0
Name                       0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [145]:
#filling the null values in review rating with the median of the specific category

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
df.isnull().sum()

Customer ID               0
Name                      0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [151]:
df.describe()

,customer_id,age,purchase_amount,review_rating,previous_purchases,purchase_frequency
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.087436,59.764359,3.750051,25.351538,89.133077
std,1125.977353,15.215450,23.685392,0.713590,14.447125,119.037566
min,1.000000,18.000000,20.000000,2.500000,1.000000,7.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000,14.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000,30.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,90.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000,365.000000

In [146]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [147]:
df.columns

Index(['customer_id', 'name', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [148]:
#create new column
labels=['Young Adult','Adult','MiddleAge','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)
df[['age','age_group']].head(10)

   age    age_group
0   56    MiddleAge
1   69       Senior
2   46    MiddleAge
3   32        Adult
4   60       Senior
5   25  Young Adult
6   38        Adult
7   56    MiddleAge
8   36        Adult
9   40        Adult

In [149]:
#create new column purchase_frequency

frequency_map={'Fortnightly':14,
              'Weekly':7,
              'Monthly':30,
              'Quarterly':90,
              'Bi-Weekly':14,
              'Annually':365,
              'Every 3 Months':90}
df['purchase_frequency'] = df['frequency_of_purchases'].map(frequency_map)
df[['purchase_frequency','frequency_of_purchases']].head()

   purchase_frequency frequency_of_purchases
0                  14            Fortnightly
1                  14            Fortnightly
2                   7                 Weekly
3                   7                 Weekly
4                 365               Annually

In [150]:
(df['discount_applied'] == df['promo_code_used']).all()

# Dropping promo code used column
df = df.drop('promo_code_used', axis=1)
df.columns

df.to_csv("customer_shopping_new.csv", index=False)

print("File saved: customer_shopping_new.csv")

File saved: customer_shopping_new.csv

,customer_id,name,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency
0,1,Diya Sharma,56,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,MiddleAge,14
1,2,Isha Gupta,69,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Senior,14
2,3,Kabir Singh,46,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,MiddleAge,7
3,4,Diya Roy,32,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Adult,7
4,5,Anaya Joshi,60,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Senior,365

In [126]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("customer_shopping_behavior.csv")

engine = create_engine("sqlite:///:memory:")

df.to_sql("customer", engine, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM customer LIMIT 5", engine)

,Customer ID,Name,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,Diya Sharma,56,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,Isha Gupta,69,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,Kabir Singh,46,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,Diya Roy,32,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,Anaya Joshi,60,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [127]:
#Q1. What is the total revenue generated by male vs. female customers?

pd.read_sql("""
SELECT gender,
SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY gender;
""", engine)

   Gender  revenue
0  Female    75191
1    Male   157890

In [103]:
#Q2. Which customers used a discount but still spent more than the average purchase amount? 

pd.read_sql("""
SELECT "Customer ID",
       "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" >= (
    SELECT AVG("Purchase Amount (USD)")
    FROM customer
);
""", engine)

     Customer ID  Purchase Amount (USD)
0              2                     64
1              3                     73
2              4                     90
3              7                     85
4              9                     97
..           ...                    ...
834         1667                     64
835         1671                     73
836         1673                     73
837         1674                     62
838         1676                     90

[839 rows x 2 columns]

In [105]:
#Q3. Which are the top 5 products with the highest average review rating?

pd.read_sql("""
SELECT "Item Purchased",
ROUND(AVG("Review Rating"), 2) AS Average_Product_Rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;
""", engine)

  Item Purchased  Average_Product_Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.79

In [106]:
#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

pd.read_sql("""
SELECT "Shipping Type",
ROUND(AVG("Purchase Amount (USD)"),2) AS avg_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard','Express')
GROUP BY "Shipping Type";
""", engine)

  Shipping Type  avg_purchase
0       Express         60.48
1      Standard         58.46

In [107]:
#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

pd.read_sql("""
SELECT "Subscription Status",
       COUNT("Customer ID") AS total_customers,
       ROUND(AVG("Purchase Amount (USD)"),2) AS avg_spend,
       ROUND(SUM("Purchase Amount (USD)"),2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC, avg_spend DESC;
""", engine)

  Subscription Status  total_customers  avg_spend  total_revenue
0                  No             2847      59.87       170436.0
1                 Yes             1053      59.49        62645.0

In [75]:
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?

pd.read_sql("""
SELECT item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
""", engine)

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [109]:
#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

pd.read_sql("""
WITH customer_type AS (
SELECT "Customer ID",
       "Previous Purchases",
CASE
    WHEN "Previous Purchases" = 1 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
FROM customer
)

SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;
""", engine)

  customer_segment  Number of Customers
0            Loyal                 3116
1              New                   83
2        Returning                  701

In [110]:
#Q8. What are the top 3 most purchased products within each category? 

pd.read_sql("""
WITH item_counts AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY "Category"
               ORDER BY COUNT("Customer ID") DESC
           ) AS item_rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT item_rank,
       "Category",
       "Item Purchased",
       total_orders
FROM item_counts
WHERE item_rank <= 3;
""", engine)

    item_rank     Category Item Purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing          Pants           171
4           2     Clothing         Blouse           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [111]:
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

pd.read_sql("""
SELECT "Subscription Status",
       COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";
""", engine)

  Subscription Status  repeat_buyers
0                  No           2518
1                 Yes            958

In [112]:
#Q10. What is the revenue contribution of each age group? 

pd.read_sql("""
SELECT
"Age Group",
SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age Group"
ORDER BY total_revenue DESC;
""", engine)

  "Age Group"  total_revenue
0   Age Group         233081